# Generated by Django 4.2.3 on 2023-11-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_employee',
        ),
    ]
